import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import NavDock from "@/components/nav/NavDock"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="zh-CN">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-slate-200`}>
        {/* Skip to content: 可键盘聚焦的跳转链接（默认隐藏，聚焦时显示）*/}
        <a
          href="#main-content"
          className="fixed left-3 top-2 -translate-y-full focus:translate-y-0 transition-transform z-[100] rounded bg-white px-3 py-2 text-sm font-medium text-black shadow focus:outline-none focus:ring-2 focus:ring-white/70"
       >
          跳转到主内容
        </a>

        {/* Global GooeyNav Navigation */}
        <NavDock />
        {/* 移除全局占位，由各页面自行通过内边距处理与导航的间距，以避免顶部出现独立的黑色带 */}

        {/* Skip link 目标：放在导航占位之后，保证滚动与聚焦位置合理 */}
        <div id="main-content" tabIndex={-1} className="contents" />

        {children}
      </body>
    </html>
  )
}
